### ISSUE TITLE
Can't communicate with spotify (Invalid response format - error #105)

### ISSUE THREAD

**Issue by robertoost** [lufinkey/spotify-token-refresh-php#1]
I took the advice from [react-native-spotify issue #4](https://github.com/lufinkey/react-native-spotify/issues/4), and didn't really get any further. The only difference is the error I'm receiving, saying my response format is wrong.

```
{ code: 105, message: "Invalid response format", domain: "RCTSpotifyErrorDomain" }
```

I tried implementing this in my own react-native app and the example project respectively, but they both produce the same result. The php server I'm running gives this output:

```
Invalid request (Unexpected EOF)
```

Approaching the php server directly does give me feedback, so I can confirm that the server is running correctly.

So although the error message is different this time ( it was previously "Could not communicate with server" ), I'm still stuck at the same point. Do you have any idea what could be causing this?

**Comment by lufinkey** [comment]
Could you please post the actual arguments you were supplying to the Spotify.initialize method, and please post your appinfo.php file? I can't make guesses to how your environment is set up.

**Comment by robertoost** [comment]
Thanks for the help, closing this issue as it seems it was not a problem with the php server after all.
